"""empty message

Revision ID: c600269c1c74
Revises: 
Create Date: 2026-04-01 09:07:00.988745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c600269c1c74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('company_size', sa.String(length=50), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=False),
    sa.Column('current_situation', sa.String(length=200), nullable=False),
    sa.Column('looking_for', sa.String(length=200), nullable=False),
    sa.Column('budget', sa.String(length=50), nullable=False),
    sa.Column('timeline', sa.String(length=50), nullable=False),
    sa.Column('is_decision_maker', sa.String(length=100), nullable=False),
    sa.Column('project_description', sa.Text(), nullable=False),
    sa.Column('how_heard', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('is_hot', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    # ### end Alembic commands ###
